import {
  type Certification,
  type Education,
  type ParsedCVData,
  type WorkExperience,
} from "@/types/cv";
import { escapeLatex } from "@/lib/pdf/latex-escape";

function e(s: string | undefined | null): string {
  return escapeLatex((s ?? "").toString());
}

function splitName(full: string): { first: string; last: string } {
  const t = full.trim();
  if (!t) return { first: "", last: "" };
  const parts = t.split(/\s+/);
  if (parts.length === 1) return { first: "", last: parts[0]! };
  return {
    first: parts.slice(0, -1).join(" "),
    last: parts[parts.length - 1]!,
  };
}

/** Avoids placeholder chains like "— -- —" when dates are missing. */
function formatWorkDateRange(job: WorkExperience): string {
  const start = (job.start_date || "").trim();
  const end = (job.end_date || "").trim();
  if (job.current) {
    if (start) return `${start} -- Present`;
    return "Present";
  }
  if (start && end) return `${start} -- ${end}`;
  if (start) return start;
  if (end) return end;
  return "";
}

function educationLooksInProgress(ed: Education): boolean {
  const blob = `${ed.degree} ${ed.field_of_study}`.toLowerCase();
  return /\b(in progress|ongoing|expected)\b/.test(blob);
}

function formatEducationDateRange(ed: Education): string {
  const start = (ed.start_date || "").trim();
  const end = (ed.end_date || "").trim();
  const inProgress = educationLooksInProgress(ed);

  if (!start && !end) {
    if (inProgress) return "Present";
    return "";
  }
  if (start && end) return `${start} -- ${end}`;
  if (start && !end) return inProgress ? `${start} -- Present` : start;
  if (!start && end) return end;
  return "";
}

function normalizeCertKey(name: string): string {
  return name.trim().toLowerCase().replace(/\s+/g, " ");
}

/** Structured certs first; add skill-string certs only when not already covered (no duplicate section). */
function mergeCertifications(data: ParsedCVData): Certification[] {
  const out: Certification[] = [];
  const seen = new Set<string>();

  for (const c of data.certifications || []) {
    if (!c.name?.trim()) continue;
    const key = normalizeCertKey(c.name);
    if (seen.has(key)) continue;
    seen.add(key);
    out.push({
      name: c.name.trim(),
      issuer: c.issuer ?? "",
      date: c.date,
      credential_id: c.credential_id,
    });
  }

  for (const s of data.skills.certifications || []) {
    if (!s?.trim()) continue;
    const key = normalizeCertKey(s);
    if (seen.has(key)) continue;
    seen.add(key);
    out.push({ name: s.trim(), issuer: "" });
  }

  return out;
}

function linkedinHandle(raw: string | undefined): string | undefined {
  if (!raw?.trim()) return undefined;
  const s = raw.trim();
  const m = s.match(/linkedin\.com\/in\/([^/?#]+)/i);
  if (m?.[1]) return decodeURIComponent(m[1].replace(/\/$/, ""));
  return s.replace(/^@/, "");
}

function homepageArg(raw: string | undefined): string | undefined {
  if (!raw?.trim()) return undefined;
  const s = raw.trim();
  if (s.startsWith("http://") || s.startsWith("https://")) return s;
  return `https://${s}`;
}

/** Self-contained resume.tex body compatible with Awesome-CV (requires awesome-cv.cls on path). */
export function buildAwesomeCvLatex(data: ParsedCVData, cvName: string): string {
  const p = data.personal_info;
  const { first, last } = splitName(p.full_name);
  const positionText = e(
    data.work_experience[0]?.position ||
      "Professional"
  );
  const addr = e(p.location || "");
  const li = linkedinHandle(p.linkedin);

  const lines: string[] = [
    `%!TEX TS-program = xelatex`,
    `%!TEX encoding = UTF-8 Unicode`,
    `% Generated by BoostMyCV — template: Awesome-CV (${e(cvName)})`,
    `% Requires awesome-cv.cls from https://github.com/posquit0/Awesome-CV`,
    ``,
    `\\documentclass[11pt, a4paper]{awesome-cv}`,
    `\\geometry{left=1.4cm, top=.8cm, right=1.4cm, bottom=1.8cm, footskip=.5cm}`,
    `\\colorlet{awesome}{awesome-skyblue}`,
    `\\setbool{acvSectionColorHighlight}{true}`,
    `\\renewcommand{\\acvHeaderSocialSep}{\\quad\\textbar\\quad}`,
    ``,
    `\\name{${e(first)}}{${e(last)}}`,
    `\\position{${positionText}}`,
  ];

  if (addr) lines.push(`\\address{${addr}}`);
  if (p.phone?.trim()) lines.push(`\\mobile{${e(p.phone)}}`);
  if (p.email?.trim()) lines.push(`\\email{${e(p.email)}}`);

  const home = homepageArg(p.portfolio);
  if (home) lines.push(`\\homepage{${e(home)}}`);
  if (li) lines.push(`\\linkedin{${e(li)}}`);

  lines.push(
    ``,
    `\\begin{document}`,
    ``,
    `\\makecvheader[C]`,
    ``,
    `\\makecvfooter`,
    `  {\\today}`,
    `  {${e(p.full_name || cvName)}~~~·~~~Résumé}`,
    `  {\\thepage}`,
    ``
  );

  if (data.professional_summary?.trim()) {
    lines.push(`\\cvsection{Summary}`);
    lines.push(`\\begin{cvparagraph}`);
    lines.push(e(data.professional_summary.trim()));
    lines.push(`\\end{cvparagraph}`);
    lines.push(``);
  }

  if (data.work_experience.length > 0) {
    lines.push(`\\cvsection{Experience}`);
    lines.push(`\\begin{cventries}`);
    for (const job of data.work_experience) {
      const bullets = [...job.responsibilities, ...job.achievements].filter((x) => x?.trim());
      const dateStr = formatWorkDateRange(job);
      const loc = e(job.location || "");
      lines.push(`  \\cventry`);
      lines.push(`    {${e(job.position)}}`);
      lines.push(`    {${e(job.company)}}`);
      lines.push(`    {${loc}}`);
      lines.push(`    {${e(dateStr)}}`);
      if (bullets.length === 0) {
        lines.push(`    {}`);
      } else {
        lines.push(`    {`);
        lines.push(`    \\begin{cvitems}`);
        for (const b of bullets) {
          lines.push(`      \\item {${e(b.trim())}}`);
        }
        lines.push(`    \\end{cvitems}`);
        lines.push(`    }`);
      }
    }
    lines.push(`\\end{cventries}`);
    lines.push(``);
  }

  if (data.education.length > 0) {
    lines.push(`\\cvsection{Education}`);
    lines.push(`\\begin{cventries}`);
    for (const ed of data.education) {
      const degreeLine = [ed.degree, ed.field_of_study].filter(Boolean).join(" — ");
      const dateStr = formatEducationDateRange(ed);
      const honors = (ed.honors || []).filter((x) => x?.trim());
      lines.push(`  \\cventry`);
      lines.push(`    {${e(degreeLine || ed.institution)}}`);
      lines.push(`    {${e(ed.institution)}}`);
      lines.push(`    {}`);
      lines.push(`    {${e(dateStr)}}`);
      if (honors.length === 0 && !ed.gpa?.trim()) {
        lines.push(`    {}`);
      } else {
        lines.push(`    {`);
        lines.push(`    \\begin{cvitems}`);
        if (ed.gpa?.trim()) lines.push(`      \\item {GPA: ${e(ed.gpa.trim())}}`);
        for (const h of honors) lines.push(`      \\item {${e(h.trim())}}`);
        lines.push(`    \\end{cvitems}`);
        lines.push(`    }`);
      }
    }
    lines.push(`\\end{cventries}`);
    lines.push(``);
  }

  const skillBlocks: { label: string; values: string[] }[] = [];
  if (data.skills.technical?.length)
    skillBlocks.push({ label: "Technical", values: data.skills.technical });
  if (data.skills.soft?.length)
    skillBlocks.push({ label: "Soft skills", values: data.skills.soft });
  if (data.skills.languages?.length)
    skillBlocks.push({ label: "Languages", values: data.skills.languages });

  if (skillBlocks.length > 0) {
    lines.push(`\\cvsection{Skills}`);
    lines.push(`\\begin{cvskills}`);
    for (const block of skillBlocks) {
      const joined = e(block.values.filter(Boolean).join(", "));
      lines.push(`  \\cvskill{${e(block.label)}}{${joined}}`);
    }
    lines.push(`\\end{cvskills}`);
    lines.push(``);
  }

  if (data.projects.length > 0) {
    lines.push(`\\cvsection{Projects}`);
    lines.push(`\\begin{cventries}`);
    for (const proj of data.projects) {
      const tech = (proj.technologies || []).filter(Boolean).join(", ");
      const dateStr = ""; // ParsedCVData has no project dates
      lines.push(`  \\cventry`);
      lines.push(`    {${e(proj.name)}}`);
      lines.push(`    {${e(tech || "Project")}}`);
      lines.push(`    {}`);
      lines.push(`    {${e(dateStr)}}`);
      const desc = proj.description?.trim();
      const url = proj.url?.trim();
      const pieces: string[] = [];
      if (desc) pieces.push(desc);
      if (url) pieces.push(url);
      if (pieces.length === 0) {
        lines.push(`    {}`);
      } else {
        lines.push(`    {`);
        lines.push(`    \\begin{cvitems}`);
        for (const piece of pieces) lines.push(`      \\item {${e(piece)}}`);
        lines.push(`    \\end{cvitems}`);
        lines.push(`    }`);
      }
    }
    lines.push(`\\end{cventries}`);
    lines.push(``);
  }

  const mergedCerts = mergeCertifications(data);
  if (mergedCerts.length > 0) {
    lines.push(`\\cvsection{Certificates}`);
    lines.push(`\\begin{cvhonors}`);
    for (const c of mergedCerts) {
      lines.push(`  \\cvhonor`);
      lines.push(`    {${e(c.name)}}`);
      lines.push(`    {${e(c.issuer || "")}}`);
      lines.push(`    {${e(c.credential_id || "")}}`);
      lines.push(`    {${e(c.date || "")}}`);
    }
    lines.push(`\\end{cvhonors}`);
    lines.push(``);
  }

  if (data.awards?.length) {
    lines.push(`\\cvsection{Awards}`);
    lines.push(`\\begin{cvhonors}`);
    for (const a of data.awards) {
      if (!a?.trim()) continue;
      lines.push(`  \\cvhonor`);
      lines.push(`    {${e(a.trim())}}`);
      lines.push(`    {}`);
      lines.push(`    {}`);
      lines.push(`    {}`);
    }
    lines.push(`\\end{cvhonors}`);
    lines.push(``);
  }

  if (data.publications?.length) {
    lines.push(`\\cvsection{Publications}`);
    lines.push(`\\begin{cvparagraph}`);
    lines.push(
      data.publications
        .filter((x) => x?.trim())
        .map((x) => `\\textbullet\\ ${e(x.trim())}`)
        .join("\\\\\n\n")
    );
    lines.push(`\\end{cvparagraph}`);
    lines.push(``);
  }

  if (data.volunteer_experience?.length) {
    lines.push(`\\cvsection{Volunteer}`);
    lines.push(`\\begin{cvparagraph}`);
    lines.push(
      data.volunteer_experience
        .filter((x) => x?.trim())
        .map((x) => `\\textbullet\\ ${e(x.trim())}`)
        .join("\\\\\n\n")
    );
    lines.push(`\\end{cvparagraph}`);
  }

  lines.push(`\\end{document}`);
  lines.push(``);

  return lines.join("\n");
}
